name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t otaviomedeiros/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true otaviomedeiros/react-test npm test
      
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-react
          environment_name: Dockerreact-env
          version_label: ${{ github.sha }}
          region: us-west-2
          deployment_package: deploy.zip
          existing_bucket_name: elasticbeanstalk-us-west-2-910995218760